services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build  # Make sure this points to the correct build output directory
    routes:
      - type: rewrite
        source: /*
        destination: /index.html